# Generated by Django 3.0.6 on 2020-05-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_id', models.CharField(editable=False, max_length=500, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('alt_phone_no', models.CharField(blank=True, max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
